version: 0.2

phases:
  pre_build:
    commands:
      - npm install -g yarn
      - yarn install
  build:
    commands:
      - yarn run build
      - ./bin/publish_to_s3.sh
cache:
  paths:
    - node_modules/**/*
