name: Publish To GitHub Packages
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Publish to NPM
      run: |
        npm install
        npm run build
        npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        npm publish --ignore-scripts --access public
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@britecore'
    - run: npm install
    - run: npm publish --ignore-scripts
      name: Publish to GitHub
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
